### ISSUE TITLE
Wiring documentation issue 

### ISSUE THREAD

**Issue by leopard3l** [jgillula/rpi-rfm69#16]
Hello

I followed this documentation to wire my Raspberry Pi B+ to the RFM69HCW radio
https://rpi-rfm69.readthedocs.io/en/latest/hookup.html

But when using this code to create a Radio instance

`with Radio(FREQ_433MHZ, node_id, network_id, isHighPower=True, verbose=False, interruptPin=28, resetPin=29, spiDevice=0, autoAcknowledge=False) as radio:`

I had the error "the channel sent is invalid on the raspberry pi" as described here:
https://forums.raspberrypi.com/viewtopic.php?t=85503

The wiring picture is incorrect.

The interrupt pin should be 18 and the reset pin should be 22

![image](https://user-images.githubusercontent.com/63955890/152839427-6e3f8ab3-9a1e-45e7-bd9b-64de6fb7022b.png)

![image](https://user-images.githubusercontent.com/63955890/152840370-901d1186-d002-4f8e-9656-6031e059afe6.png)

**Comment by jgillula** [comment]
Good catch! I could change the table, but unfortunately I don't have the original Fritzing files for the wiring diagram since I inherited this project from its original maintainer

@jkittley Do you by any chance still have the original Fritzing files you used to make the documentation?

**Comment by leopard3l** [comment]
Hello

I redid it in Fritzing for the Pi Zero, but it's the same wiring for other Pis

![image](https://user-images.githubusercontent.com/63955890/153721859-9e0650ef-ee77-47b9-b6f3-c50ac8dfa3f0.png)

**Comment by leopard3l** [comment]
Don't forget to correct this in the table

![image](https://user-images.githubusercontent.com/63955890/153721882-73f4e57d-d8da-40c1-ad1f-3f7761534e58.png)

**Comment by fconrotte** [comment]
Hello !

I re-checked the wiring and in fact there is still a small mistake: the RST and G0 cables are incorrect, they must be inverted

Here is the final plan

![image](https://user-images.githubusercontent.com/4604786/157462376-6bb8c84f-80a4-4b9a-b047-912372e14297.png)

**Comment by jgillula** [comment]
Good catch! I've fixed it in the [latest docs](https://rpi-rfm69.readthedocs.io/en/latest/hookup.html)--thanks!
